[package]
name = "toy_transaction"
version = "0.1.0"
authors = ["Matthew Brown <matthewabrown@icloud.com>"]
edition = "2018"

[dependencies]
csv = "1.1.5"
serde = { version = "1", features = ["derive"] }